version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app                # Mount the current directory to /app in the container
      - /app/node_modules      # Prevents overwriting node_modules with the local folder
